export default {
  form: document.querySelector('form'),
  heading: document.querySelector('h1'),
  input: document.querySelector('input'),
  label: document.querySelector('label'),
  postsContainer: document.querySelector('.posts'),
  feedsContainer: document.querySelector('.feeds'),
  subheading: document.querySelector('.lead'),
  feedback: document.querySelector('.feedback'),
  button: document.querySelector('button[type="submit"]'),
  modalTitle: document.querySelector('.modal-title'),
  modalBody: document.querySelector('.modal-body'),
  modalFooter: document.querySelector('.modal-footer'),
  previewButtons: document.querySelectorAll('button[type="button"]'),
};
